### ISSUE TITLE
Add nvm 

### ISSUE THREAD

**Issue by NourSammour** [NourSammour/biletiniz#5]
add `.nvmrc` file with this value `10.16.0`

https://github.com/nvm-sh/nvm/blob/master/README.md#nvmrc

**Comment by dohamokdad** [comment]
$ nvm use
$ nvm install
$ nvm exec
$ nvm run
$ nvm which

$ echo "10.16.0" > .nvmrc
$ echo "lts/*" > .nvmrc # to default to the latest LTS version
$ echo "node" > .nvmrc # to default to the latest version

$ nvm use

**Comment by NourSammour** [comment]
@dohamokdad 
similar to this PR
just add .nvmrc file with this value `v10.16.0`
https://github.com/NourSammour/biletiniz/pull/6

1 file with 1 line

similar to this project
https://github.com/SimonKaya91/Weather-Server
this file
https://github.com/SimonKaya91/Weather-Server/blob/master/.nvmrc

**Comment by dohamokdad** [comment]
$ echo "10.16.0" > .nvmrc #5

**Comment by NourSammour** [comment]
https://github.com/NourSammour/biletiniz/pull/14
